#!/usr/bin/env bash
# Check record
if (( $# == 1 )); then
    for subs in www lb-01 web-01 web-02; do
        Name=$(dig "$subs.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
        IP=$(dig "$subs.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
        echo "The subdomain $subs is a $Name record and points to $IP"
    done
    elif (( $# == 2 )); then
    Name=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
    IP=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
    echo "The subdomain $2 is a $Name record and points to $IP"
fi
