#!/usr/bin/env bash
# Install nginx & output 'Holberton School' by default
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod u+x /var/www/html/index-2.html
echo "Holberton School" > /var/www/html/index-2.html
sudo service nginx restart
