#!/usr/bin/env bash
# Install nginx & output 'Holberton School' by default
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# line="location /redirect_me {rewrite ^/redirect_me(.*)$ https://juancarabalidev.com permanent;\n}"
# sudo sed -i "49i $line" /etc/nginx/sites-available/default

# config 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
errorPage=" error_page 404 /404.html;\nlocation = /404.html {\n root /var/www/html;\n internal;\n}"
sudo sed -i "52i $errorPage" /etc/nginx/sites-available/default

sudo service nginx restart
