#!/usr/bin/env bash
# setting load balancer
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt install -y haproxy

sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy

FRONT="\\\nfrontend http_front\n\tbind *:80\
\n\tmode http\n\tdefault_backend http_back"

BACK="\\nbackend http_back\n\tbalance roundrobin\
\n\tserver 2614-web-01 34.138.203.182:80 check\
\n\tserver 2614-web-02 3.91.194.210:80 check"

sudo sed -i "\$a$FRONT$BACK" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
