#!/usr/bin/env bash
# Print minute for 12 hours

hora=0
while (( hora <= 12 ));
	do
		echo "Hour: $hora"

    min=1
    while (( min < 60 ));
	do
		echo $min
	min=$(( min+=1 ))
    done

    hora=$(( hora+=1 ))
done
